travis:
  secure:
    BINSTAR_TOKEN: nDZMGBdYNuB1shWa/uZQZp16nPzh+xLW+z6aSZXc81Qa42UDWVhwjtSUwFU4dMcvAtWXEf0xeLBCuMlygMMz5Pv3/9rWaG/VBEHBJ0Yto8wDlpPyP5Mm7Ep/AKJa9lSnMXY/SsEODlji9KemfFZq4WE4X3CSw6kIK74srYocCOriUjIMiKLwfMueItWFFQk8mkOjnrFlEyxhM7uj5EeEqt443xTsDXPI56RyIQzl0v2qa/3OSIR8hCjGdGEXmyAVuxsjAJej+pZrizXlo+fhrfQs9fcblcM0tGrqE/irAfYjTZWWgVc+VRbEksdLh1e33Va8LXkSR1t8TIqdC/iY4v3C0Aq12Wb0X5YznGiw/tyRyRM+BPvApntr01nLHxeuFdJkr6QifWcDLGoGHZ6IXvMeiKBH83O+CqeByN+vWFXaZk8qTBatvpOcxgb5Ril4EK4gn4ovL2QQjuHxXmunyJP2lY8qk/zL98AxGXt+xBesIjgyJC4tZUQdEIA4KbHKaTW4M22Obg9bQICJaIDF2X4Cx0MEe7et/8n6QixZ2ZUzIRXRNk9XKlkACiIRfkvYipFUY42chKEi7T8YK29xNfIRQDq1hiNZCCUicTIVMKdL3ashc7EVl6fbGhokzCcvGwqDPntFDdfhCXzos82g4vZLxKotfRppzAc9tkoqinA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
