appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: em8vJHXKpwN1JpO6boHtz2Qti69fhEkyd122LsUgNem07tHfBO4eB2zoCnY9RLPR/uncjMbrbOIU3HbOdULvyVwD97P0lkNU6RivxseY7D3ELqoZM2maSaERYhduvn6Mq2DJ4aVGBkQhM3M8+dL1sIgwsBFlw/DDg1Xc0kSqV9bgTxkHKoiWgZiavgl3ahJcuSzWlSdfWAMLUmfR9noa4NbjCygCo2hADmLIDr/3RAUVYzAOaOuCfAFIwjjUNZyvh/qwgDZWPXUEPqrYc7OJXi9Mrw7j0HcZ5GjqS9GRLHn1je2ESDPX98W/fYV+XB1PJXflwZPVoJOFo8nnwrn+JfxpcglFdp1TRPplZ5Kgnd7hAiNjI67mNMoscLTXKL+742ZK1re4N0MakOJAzVp6Bmx9uFa2Qesq1QMEshfKcjtljbgxqZjGfFLI1UEn1HmnnAM43xIyeadfjw05GuOJ8/7E8IBc1lhNzVTW6p0o0vZ9uoXiLjzZUunct1SRh9C6LGWnYqYta3koDGPFsJsCGiFdlRMcIIOn4GL7e5Zn6n/Amm7kjPFkTWh/0W2Q08vvfScLR4b4VcP/xVLbWCVAYejmKwGWzMw6jhOL/PWJYHt4xwWIbfCrUTYzkujtOR7Gi4dz6qZjxyrynNBjdOXh2W7tUqXveL9Q0WjZ3igM0Fo=}
